src/main/default/objects/MultiReport_Export_Item__c/MultiReport_Export_Item__c.object-meta.xml
<CustomObject>
    <description>Object to Map Report to the exported xlsx sheet</description>
    <label>MultiReport Export Item</label>
    <nameField>
        <displayFormat>MR-Export-Item-{00000}</displayFormat>
        <label>MultiReport Export Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MultiReport Export Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/main/default/objects/MultiReport_Export_Item__c/fields/MultiReport_Export_Template__c.field-meta.xml
<CustomField>
    <fullName>MultiReport_Export_Template__c</fullName>
    <label>MultiReport Export Template</label>
    <referenceTo>MultiReport_Export_Template__c</referenceTo>
    <relationshipLabel>MultiReport Export Items</relationshipLabel>
    <relationshipName>MultiReport_Export_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

src/main/default/objects/MultiReport_Export_Item__c/fields/Report_Id__c.field-meta.xml
<CustomField>
    <fullName>Report_Id__c</fullName>
    <description>The Id of the Report used to create a sheet in the .xlsx export</description>
    <inlineHelpText>The Id of the Report used to create a sheet in the .xlsx export</inlineHelpText>
    <label>Report Id</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/main/default/objects/MultiReport_Export_Item__c/fields/Report_Name__c.field-meta.xml
<CustomField>
    <fullName>Report_Name__c</fullName>
    <description>The Name of the Report used to create a sheet in the .xlsx export</description>
    <inlineHelpText>The Id of the Report used to create a sheet in the .xlsx export</inlineHelpText>
    <label>Report Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/main/default/objects/MultiReport_Export_Item__c/fields/Sheet_Name__c.field-meta.xml
<CustomField>
    <fullName>Sheet_Name__c</fullName>
    <description>The Name you would like for the sheet in the .xlsx export file ( the name of the tab at the bottom in Excel )</description>
    <inlineHelpText>The Name you would like for the sheet in the .xlsx export file ( the name of the tab at the bottom in Excel )</inlineHelpText>
    <label>Sheet Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/main/default/objects/MultiReport_Export_Template__c/MultiReport_Export_Template__c.object-meta.xml
<CustomObject>
    <description>Template for creating a multiple-report export with each report on its own sheet in the .xlsx file</description>
    <label>MultiReport Export Template</label>
    <nameField>
        <label>MultiReportExport Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MultiReport Export Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/MultiReport_Export_Template__c/fields/Add_Column_Filter__c.field-meta.xml
<CustomField>
    <fullName>Add_Column_Filter__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Adds Filter menu to every column header</description>
    <inlineHelpText>Adds Filter menu to every column header</inlineHelpText>
    <label>Add Column Filter</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/MultiReport_Export_Template__c/fields/Auto_Send_Email__c.field-meta.xml
<CustomField>
    <fullName>Auto_Send_Email__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Automatically Send the Exported file via email to the specified Recipients using the specified Email Template</description>
    <inlineHelpText>Automatically Send the Exported file via email to the specified Recipients using the specified Email Template</inlineHelpText>
    <label>Auto Send Email</label>
    <type>Checkbox</type>
</CustomField>

src/main/default/objects/MultiReport_Export_Template__c/fields/Email_Recipients__c.field-meta.xml
<CustomField>
    <fullName>Email_Recipients__c</fullName>
    <description>A comma separated list on recipient email addresses</description>
    <inlineHelpText>A comma separated list on recipient email addresses</inlineHelpText>
    <label>Email Recipients</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/MultiReport_Export_Template__c/fields/Email_Template_Id__c.field-meta.xml
<CustomField>
    <fullName>Email_Template_Id__c</fullName>
    <externalId>true</externalId>
    <label>Email Template Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/MultiReport_Export_Template__c/fields/Export_File_Name__c.field-meta.xml
<CustomField>
    <fullName>Export_File_Name__c</fullName>
    <description>The name of the file that will be exported</description>
    <label>Export File Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

src/main/default/classes/controllers/MultiReportRunExportController.cls
public with sharing class MultiReportRunExportController {
  @AuraEnabled
  public static MultiReport_Export_Template__c getTemplateAndItems(
    String templateId
  ) {
    return [
      SELECT
        Id,
        Name,
        Export_File_Name__c,
        Email_Template_Id__c,
        Email_Recipients__c,
        Auto_Send_Email__c,
        Add_Column_Filter__c,
        (
          SELECT Id, Report_Id__c, Report_Name__c, Sheet_Name__c
          FROM MultiReport_Export_Items__r
        )
      FROM MultiReport_Export_Template__c
      WHERE Id = :templateId
    ];
  }

  @AuraEnabled
  public static Report2XlsxSheet getReportData(String exportItemId) {
    return new Report2XlsxSheet(exportItemId).run();
  }

  @AuraEnabled
  public static void sendFileInEmail(Map<String, String> emailData) {
    List<String> toAddresses = emailData.get('recipients').split(',');
    Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
    Blob fileBlob = EncodingUtil.base64Decode(emailData.get('base64'));
    Messaging.EmailFileAttachment efa = new Messaging.EmailFileAttachment();
    efa.setFileName(emailData.get('fileName'));
    efa.setBody(fileBlob);
    email.setToAddresses(toAddresses);
    email.setTargetObjectId(UserInfo.getUserId());
    email.setSaveAsActivity(false);
    email.setTemplateId(emailData.get('emailTemplateId'));
    email.setFileAttachments(new List<Messaging.EmailFileAttachment>{ efa });
    if (Application_Settings.getInstance().emailDeliverabilityEnabled()) {
      Messaging.sendEmail(new List<Messaging.SingleEmailMessage>{ email });
    }
  }
}