src/main/default/objects/MultiReport_Export_Template__c/MultiReport_Export_Template__c.object-meta.xml
<CustomObject>
    <description>Template for creating a multiple-report export with each report on its own sheet in the .xlsx file</description>
    <label>MultiReport Export Template</label>
    <nameField>
        <label>MultiReportExport Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MultiReport Export Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/main/default/objects/MultiReport_Export_Template__c/fields/Email_Template_Id__c.field-meta.xml
<CustomField>
    <fullName>Email_Template_Id__c</fullName>
    <externalId>true</externalId>
    <label>Email Template Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

src/main/default/objects/MultiReport_Export_Template__c/fields/Email_Template_Name__c.field-meta.xml
<CustomField>
    <fullName>Email_Template_Name__c</fullName>
    <description>Name of the Email template used to send the Export</description>
    <inlineHelpText>Name of the Email template used to send the Export</inlineHelpText>
    <label>Email Template Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

src/main/default/classes/triggerHandlers/MultiReportExportTemplate/TA_MRExportTemplate_ValidateEmail.cls
public without sharing class TA_MRExportTemplate_ValidateEmail implements TriggerAction.BeforeInsert, TriggerAction.BeforeUpdate {
  public void beforeInsert(List<MultiReport_Export_Template__c> newList) {
    Set<String> templateNames = new Set<String>();
    for (MultiReport_Export_Template__c mret : newList) {
      if (mret.Email_Template_Name__c != null) {
        templateNames.add(mret.Email_Template_Name__c);
      }
    }
    findAndSetEmailTemplates(newList, templateNames, null);
  }

  public void beforeUpdate(
    List<MultiReport_Export_Template__c> newList,
    List<MultiReport_Export_Template__c> oldList
  ) {
    Map<Id, MultiReport_Export_Template__c> oldMap = new Map<Id, MultiReport_Export_Template__c>(
      oldList
    );
    Set<Id> recordIdsWithChangedEmailTemplates = new Set<Id>();
    Set<String> templateNames = new Set<String>();
    for (MultiReport_Export_Template__c mret : newList) {
      MultiReport_Export_Template__c oldRecord = oldMap.get(mret.Id);
      if (
        mret.Email_Template_Name__c == null &&
        oldRecord.Email_Template_Name__c != null
      ) {
        mret.Email_Template_Id__c = null;
        continue;
      }
      if (mret.Email_Template_Name__c != oldRecord.Email_Template_Name__c) {
        templateNames.add(mret.Email_Template_Name__c);
        recordIdsWithChangedEmailTemplates.add(mret.Id);
      }
    }
    findAndSetEmailTemplates(
      newList,
      templateNames,
      recordIdsWithChangedEmailTemplates
    );
  }

  private void findAndSetEmailTemplates(
    List<MultiReport_Export_Template__c> newList,
    Set<String> templateNames,
    Set<Id> recordIdsWithChanges
  ) {
    if (templateNames.size() > 0) {
      Map<String, EmailTemplate> templatesByName = new Map<String, EmailTemplate>();
      for (EmailTemplate et : [
        SELECT Id, Name
        FROM EmailTemplate
        WHERE Name IN :templateNames
      ]) {
        templatesByName.put(et.Name, et);
      }
      for (MultiReport_Export_Template__c mret : newList) {
        if (
          recordIdsWithChanges == null || recordIdsWithChanges.contains(mret.Id)
        ) {
          if (
            mret.Email_Template_Name__c != null &&
            templatesByName.containsKey(mret.Email_Template_Name__c)
          ) {
            mret.Email_Template_Id__c = templatesByName.get(
                mret.Email_Template_Name__c
              )
              .Id;
          }
          if (
            mret.Email_Template_Name__c != null &&
            !templatesByName.containsKey(mret.Email_Template_Name__c)
          ) {
            mret.addError(
              'Could not find the Email Template "' +
                mret.Email_Template_Name__c +
                '"'
            );
          }
        }
      }
    }
  }
}